import {testProcessProject} from '../generate';

testProcessProject(
  'does not touch .guard.ts files that are not autogenerated',
  { 'test.guard.ts': `alert("hello")` },
  { 'test.guard.ts': null }
)